# Site settings
title: Mt. Sugoi 
email: robertwilson1024@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website of Mt. Sugoi

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mtsugoi.com" # the base hostname & protocol for your site
twitter_username: mt_sugoi
github_username:  phuidn

# Build settings
markdown: kramdown
